[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chat_common = { path = "../common" }
futures = "0.3.0"
async-std = "1"
crossterm = "0.27.0"